logging {
  level = sys.env("LOG_LEVEL")
  format = "logfmt"
}

otelcol.auth.bearer "incoming" {
  token = sys.env("OTLP_RECEIVER_BEARER_TOKEN")
}

otelcol.receiver.otlp "default" {
  http {
    endpoint = "0.0.0.0:4318"
    auth = otelcol.auth.bearer.incoming.handler
  }

  grpc {
    endpoint = "0.0.0.0:4317"
    auth = otelcol.auth.bearer.incoming.handler
  }

  output {
    metrics = [otelcol.processor.batch.default.input]
    logs    = [otelcol.processor.batch.default.input]
    traces  = [otelcol.processor.batch.default.input]
  }

}

otelcol.processor.batch "default" {
  output {
    metrics = [otelcol.processor.attributes.default.input]
    logs    = [otelcol.processor.attributes.default.input]
    traces  = [otelcol.processor.attributes.default.input]
  }
}

otelcol.processor.attributes "default" {
  action {
    key = "deployment.environment"
    value = sys.env("ATTR_DEPLOYMENT_ENVIRONMENT_NAME")
    action = "insert"
  }

  output {
    metrics = [otelcol.exporter.otlphttp.default.input]
    logs    = [otelcol.exporter.otlphttp.default.input]
    traces  = [otelcol.exporter.otlphttp.default.input]
  }
}

otelcol.auth.basic "default" {
  username = sys.env("OTLP_BASIC_AUTH_USERNAME")
  password = sys.env("OTLP_BASIC_AUTH_PASSWORD")
}

otelcol.exporter.otlphttp "default" {
  client {
    endpoint = sys.env("OTLP_ENDPOINT")
    auth     = otelcol.auth.basic.default.handler
  }
}
