name: Rebuild on Upstream Update

on:
  schedule:
    - cron: '0 6 * * *' # Runs daily at 6am UTC
  workflow_dispatch:

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest upstream tag
        id: get_tag
        uses: lucacome/docker-image-tag-action@v1
        with:
          image: grafana/alloy

      - name: Read last built tag
        id: last_tag
        run: |
          echo "LAST_TAG=$(cat .last_built_tag 2>/dev/null || echo 'none')" >> $GITHUB_ENV

      - name: Compare tags
        id: compare
        run: |
          if [ "${{ steps.get_tag.outputs.tag }}" != "${{ env.LAST_TAG }}" ]; then
            echo "new_tag=true" >> $GITHUB_OUTPUT
          else
            echo "new_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push image
        if: steps.compare.outputs.new_tag == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/alloy-custom:${{ steps.get_tag.outputs.tag }}
          build-args: |
            ALLOY_TAG=${{ steps.get_tag.outputs.tag }}

      - name: Update last built tag
        if: steps.compare.outputs.new_tag == 'true'
        run: echo "${{ steps.get_tag.outputs.tag }}" > .last_built_tag

      - name: Commit and push .last_built_tag
        if: steps.compare.outputs.new_tag == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update last built tag
          file_pattern: .last_built_tag